#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title difficulty
graph_vlabel difficulty
graph_category boolb
difficulty.label difficulty
EOM
        exit 0;;
esac

printf "difficulty.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=10102 --timeout=1000 --rpc_get_daemon_info | grep difficulty | cut -d ' ' -f2
