#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title Height
graph_vlabel height
graph_category boolb
height.label height
height.type COUNTER
EOM
        exit 0;;
esac

printf "height.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=10102 --timeout=1000 --rpc_get_daemon_info | grep height | cut -d ' ' -f2
