#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title difficulty
graph_vlabel difficulty
graph_category luid
pow_difficulty.label pow_difficulty

EOM
        exit 0;;
esac

printf "pow_difficulty.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=11112 --timeout=1000 --rpc_get_daemon_info | grep pow_difficulty | cut -d ' ' -f2
