#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title seconds_per_n_blocks
graph_vlabel seconds_per_n_blocks
graph_category luid
seconds_per_10_blocks.label seconds_per_10_blocks
seconds_per_30_blocks.label seconds_per_30_blocks
EOM
        exit 0;;
esac

printf "seconds_per_10_blocks.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=11112 --timeout=1000 --rpc_get_daemon_info | grep seconds_between_10_blocks | cut -d ' ' -f2
printf "seconds_per_30_blocks.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=11112 --timeout=1000 --rpc_get_daemon_info | grep seconds_between_30_blocks | cut -d ' ' -f2
