#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_sequense sequense
graph_vlabel sequense
graph_category luid
pos_sequense_factor.label pos_sequense_factor
pow_sequense_factor.label pow_sequense_factor
EOM
        exit 0;;
esac

printf "pos_sequense_factor.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=11112 --timeout=1000 --rpc_get_daemon_info | grep pos_sequense_factor | cut -d ' ' -f2
printf "pow_sequense_factor.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=11112 --timeout=1000 --rpc_get_daemon_info | grep pow_sequense_factor | cut -d ' ' -f2
