#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_sequense sequense
graph_vlabel sequense
graph_category luid
alias_count.label sequense
EOM
        exit 0;;
esac

printf "sequense.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=10102 --timeout=1000 --rpc_get_daemon_info | grep sequense | cut -d ' ' -f2
