#!/bin/bash

case $1 in
   config)
        cat <<'EOM'
graph_title tx_daily_volume
graph_vlabel tx_daily_volume
graph_category boolb
tx_daily_volume.label tx_daily_volume
EOM
        exit 0;;
esac

printf "tx_daily_volume.value "
connectivity_tool --ip=127.0.0.1 --rpc_port=10102 --timeout=1000 --rpc_get_daemon_info | grep transactions_volume_per_day | cut -d ' ' -f2
